---
- name: Setup
  hosts: dest[0]
  tasks:
    - name: Ensure python3 and python3-pip is present
      ansible.builtin.package:
        name: 
          - python3
          - python3-pip
        state: present
      become: true
      become_user: root

    - name: Install the latest pymongo package
      pip: name=pymongo state=latest 

    - name: Cutover Mongo Cluster Primary Node
      script:
        executable: python3
        cmd: ../files/cutover.py {{ groups |  to_json | b64encode }}
      register: output

    - name: Print Mongo Cluster Member Nodes Status
      debug:
        msg: "{{ output.stdout_lines[0] }}"
