---
- name: Setup MongoDB Migration
  hosts: all
  gather_facts: yes
  vars:
    migration_dir: /opt/mongo-migration
    local_files_dir: "{{ playbook_dir }}/../files"

  tasks:
    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        update_cache: yes
        name:
          - python3
          - python3-pip
          - python3-dev
          - libssl-dev
          - libffi-dev
        state: present

    - name: Install pymongo with pip
      become: true
      pip:
        name:
          - pymongo
          - dnspython
        state: latest

    - name: Create migration directory
      ansible.builtin.file:
        path: "{{ migration_dir }}"
        state: directory
        mode: '0755'
      become: true

    - name: Copy migration scripts
      ansible.builtin.copy:
        src: "{{ local_files_dir }}/{{ item }}"
        dest: "{{ migration_dir }}/"
        mode: '0755'
      loop:
        - validate.py
        - setup.py