---
- name: Setup
  hosts: dest[0]
  tasks:
    - name: Ensure python3 and python3-pip is present
      ansible.builtin.package:
        name: 
          - python3
          - python3-pip
        state: present
      become: true
      become_user: root

    - name: Install the latest pymongo package
      pip: name=pymongo state=latest 

    - name: Check Mongo Cluster Nodes Status
      script:
        executable: python3
        cmd: ../files/status.py {{ groups |  to_json | b64encode }}
      register: output

    - name: Print python script executable output
      debug:
        msg: "{{ output.stdout_lines[0] }}"