---
- name: Validate
  hosts: dest[0]
  tasks:
    - name: Ensure python3 and python3-pip is present
      ansible.builtin.package:
        name: 
          - python3
          - python3-pip
        state: present
      become: true
      become_user: root

    - name: Install the latest pymongo package
      pip: name=pymongo state=latest 

    - name: Mongo Cluster Data Validation
      script:
        executable: python3
        cmd: ../files/validate.py {{ groups |  to_json | b64encode }}
      register: output

    - name: Mongo Cluster Data Validation Status 
      debug:
        msg: "{{ output.stdout_lines[0] }}"

    - name: DATA VALIDATION PASSED
      debug:
        msg: "DATA VALIDATION PASSED Successfully"
      when: '"FAILED" not in output.stdout'

    - name: DATA VALIDATION FAILED
      fail:
        msg: "DATA VALIDATION FAILED"
      when: '"FAILED" in output.stdout'

