include: .vars.yml
stages:
  - mongodb-migration

mongodb-migration:
  image: 'asia.gcr.io/systems-0001/ansible:ubuntu20.04'
  stage: mongodb-migration
      
  
  before_script:
    - |
       cp files/before_script.sh /tmp/ && chmod +x /tmp/before_script.sh
       . /tmp/before_script.sh        

  script:  
    - |
       . /tmp/run.sh  

  only:
      - update-runner-tag
      
  tags:
    - migration-factory

  when: manual
  
